### ISSUE TITLE
Cannot reference action using @v1

### ISSUE THREAD

**Issue by rickselby** [university-of-york/aws-cdk-deploy-action#17]
To get this running in a workflow, I've had to specify an exact version: `university-of-york/aws-cdk-deploy-action@v1.0.3`

With `@v1` (or `@v1.0`), I get the following error:

> Unable to resolve action `university-of-york/aws-cdk-deploy-action@v1`, unable to find version `v1`

**Comment by natseg** [comment]
Thanks @rickselby only just saw that. Will take a look!

**Comment by natseg** [comment]
This issue has a tentative PR here for review: https://github.com/university-of-york/aws-cdk-deploy-action/pull/20.
Thanks a lot!

**Comment by natseg** [comment]
Thanks for your patience all, issue should now be fixed.
Feel free to reopen if having issues.

**Comment by rickselby** [comment]
Finally got around to testing it out (sorry), works perfectly - thank you!
