### ISSUE TITLE
Allow deployment of multiple stacks from a single app

### ISSUE THREAD

**Issue by rickselby** [university-of-york/aws-cdk-deploy-action#27]
When trying to use this action with our 'infrastructure' app, which has multiple stacks, we get the following error:

> Since this app includes more than a single stack, specify which stacks to use (wildcards are supported) or specify `--all`

Since it doesn't look like the stack name is passed to `cdk deploy`, could `-all` be added to the deploy command?

**Comment by natseg** [comment]
Thanks for opening this issue.

This might fall within the scope of that [issue](https://github.com/university-of-york/aws-cdk-deploy-action/issues/10).

I am happy to have a look into this, will update both issues @rickselby

**Comment by natseg** [comment]
This should now be deployed. Many thanks!
Please update this issue if you encounter any problems related to this feature.
